using System.Runtime.CompilerServices;
using static LightTraveller.Guards.Messages;

namespace LightTraveller.Guards;

public partial class Guard
{
    /// <summary>
    /// Throws if the input argument is zero; otherwise, returns the argument itself.
    /// </summary>
    /// <param name="param">The argument to be validated.</param>
    /// <param name="expression">The expression resolving to the value of the argument being checked. This is automatically generated by the compiler.</param>
    /// <returns>The input argument, if it passes the check.</returns>
    /// <exception cref="ArgumentException">The argument resolves to zero.</exception>
    public static int Zero(int param, string? message = null, [CallerArgumentExpression("param")] string expression = "")
    {
        if (param == 0)
            Helper.ArgumentException.Throw(message.IfEmptyThen(Messages.Zero), expression);

        return param;
    }

    /// <summary>
    /// Throws if the input argument is zero; otherwise, returns the argument itself.
    /// </summary>
    /// <param name="param">The argument to be validated.</param>
    /// <param name="expression">The expression resolving to the value of the argument being checked. This is automatically generated by the compiler.</param>
    /// <returns>The input argument, if it passes the check.</returns>
    /// <exception cref="ArgumentException">The argument resolves to zero.</exception>
    public static long Zero(long param, string? message = null, [CallerArgumentExpression("param")] string expression = "")
    {
        if (param == 0L)
            Helper.ArgumentException.Throw(message.IfEmptyThen(Messages.Zero), expression);

        return param;
    }

    /// <summary>
    /// Throws if the input argument is zero; otherwise, returns the argument itself.
    /// </summary>
    /// <param name="param">The argument to be validated.</param>
    /// <param name="expression">The expression resolving to the value of the argument being checked. This is automatically generated by the compiler.</param>
    /// <returns>The input argument, if it passes the check.</returns>
    /// <exception cref="ArgumentException">The argument resolves to zero.</exception>
    public static float Zero(float param, string? message = null, [CallerArgumentExpression("param")] string expression = "")
    {
        if (param == 0F)
            Helper.ArgumentException.Throw(message.IfEmptyThen(Messages.Zero), expression);

        return param;
    }

    /// <summary>
    /// Throws if the input argument is zero; otherwise, returns the argument itself.
    /// </summary>
    /// <param name="param">The argument to be validated.</param>
    /// <param name="expression">The expression resolving to the value of the argument being checked. This is automatically generated by the compiler.</param>
    /// <returns>The input argument, if it passes the check.</returns>
    /// <exception cref="ArgumentException">The argument resolves to zero.</exception>
    public static double Zero(double param, string? message = null, [CallerArgumentExpression("param")] string expression = "")
    {
        if (param == 0D)
            Helper.ArgumentException.Throw(message.IfEmptyThen(Messages.Zero), expression);

        return param;
    }

    /// <summary>
    /// Throws if the input argument is zero; otherwise, returns the argument itself.
    /// </summary>
    /// <param name="param">The argument to be validated.</param>
    /// <param name="expression">The expression resolving to the value of the argument being checked. This is automatically generated by the compiler.</param>
    /// <returns>The input argument, if it passes the check.</returns>
    /// <exception cref="ArgumentException">The argument resolves to zero.</exception>
    public static decimal Zero(decimal param, string? message = null, [CallerArgumentExpression("param")] string expression = "")
    {
        if (param == 0M)
            Helper.ArgumentException.Throw(message.IfEmptyThen(Messages.Zero), expression);

        return param;
    }
}